### ISSUE TITLE
Actor registration doesn't imply that method "isRegistered" returns true

### ISSUE THREAD

**Issue by hsestupin** [puniverse/quasar#100]
So it seems like a bug for me. The method **co.paralleluniverse.actors.Actor#postRegister()** only gets called if actor is registered via 

    co.paralleluniverse.actors.ActorRegistry#getOrRegisterActor(java.lang.String, java.util.concurrent.Callable<co.paralleluniverse.actors.Actor<Message,?>>, co.paralleluniverse.fibers.FiberScheduler)

Is this a correct behavior? Its really odd cause as a consequence if we register an actor with **co.paralleluniverse.actors.Actor#register(java.lang.String)** then **co.paralleluniverse.actors.Actor#isRegistered** will return false.

**Comment by pron** [comment]
Thank you. I'll take a look next week.
