### ISSUE TITLE
ASL 2.0

### ISSUE THREAD

**Issue by sirinath** [puniverse/quasar#105]
The comparison table says Quasar is licensed under EPL and ASL 2.0 but this is not reflected in the repo: http://blog.paralleluniverse.co/2015/05/21/quasar-vs-akka/

Generally consider moving your Open Source projects to ASL 2.0

**Comment by circlespainter** [comment]
Thanks for pointing out, the error is in the blog post, Quasar is EPL1 or LGPL3. I'll fix the table soon.
