### ISSUE TITLE
RequestReplyHelper#call fails with actors on one Galaxy node

### ISSUE THREAD

**Issue by hsestupin** [puniverse/quasar#111]
I've created a project to introduce this issue - https://github.com/hsestupin/quasar-galaxy-issue
To reproduce the problem you can run:
````
gradle :issue2:run
````

So I've spent some time debugging and find out why this happens. While invoking **RequestReplyHelper#call** method  **co.paralleluniverse.remote.galaxy.GlxNonGlobalRemoteActor#isNodeAlive** returns false, therefore we instantly got ExitMessage while trying to make a watch in **RequestReplyHelper#call**.

**Comment by pron** [comment]
Solved by cc7571e
