### ISSUE TITLE
Escalate Strategy always fires

### ISSUE THREAD

**Issue by jjcomer** [puniverse/quasar#117]
Not sure if this is a defect or expected behaviour, but a supervisor with the escalate strategy will always give up regardless of child type. I noticed this when one of my temporary actors naturally terminated and the whole supervisor was shutdown. The doc strings make it sound like the restart strategy should only be invoked on the death of a permanent or unnatural death of a transient.

**Comment by pron** [comment]
Sounds like a bug.
