### ISSUE TITLE
Kotlin M13 support

### ISSUE THREAD

**Issue by terrybleger** [puniverse/quasar#119]
Please support Kotlin M13.

**Comment by beihaifeiwu** [comment]
+1

**Comment by circlespainter** [comment]
What happens if you force `org.jetbrains.kotlin:kotlin-stdlib` and `org.jetbrains.kotlin:kotlin-reflect` to the M13 versions?

**Comment by terrybleger** [comment]
@circlespainter I wish it could be that simple. The codes must also be refactored to reflect breaking changes in Kotlin M13.

I'd like to create a PR, but when I downloaded the project and setup it in IDEA there's a lot of missing symbols.

**Comment by terrybleger** [comment]
Right now in my own project If I tried to not include "co.paralleluniverse:quasar-kotlin:0.7.3" in my gradle build file. So like,
```
compile 'co.paralleluniverse:quasar-core:0.7.3:jdk8'
compile 'co.paralleluniverse:quasar-actors:0.7.3'
```
I'm will getting the error of ```WARNING: Uninstrumented methods (marked '**') or call-sites (marked '!!') detected on the call stack:```

But when using Kotlin M12 and included the ```co.paralleluniverse:quasar-kotlin:0.7.3``` I won't get the error.

I thought that like most of the Kotlin 3rd party library it should not break your app, since usually the Kotlin parts are only extension methods so that it can be more Kotlin friendly. Take for example RxKotlin and Jackson, both can be used without the library extension for Kotlin.

Right now I can't continue my project at all because of this.

If somebody could help pointing me on how to compile the Quasar project without any missing symbol errors that would be helpful.

**Comment by circlespainter** [comment]
I usually use Idea too for Quasar development without any problems, which missing symbols are there? I usually just open the root `build.gradle` file (or the existing Idea project once it has been imported from Gradle).

Quasar needs to instrument fiber-blocking methods in order to implement fibers and Kotlin's callable features need specific instrumentation support in some cases: if their implementation changes, so the Quasar integration for Kotlin needs to be ported as as well but usually it involves very few and small changes.

**Comment by beihaifeiwu** [comment]
Hi, this is what happended to my project:

```
[ERROR] E:\maven_local_repositories\co\paralleluniverse\quasar-kotlin\0.7.2\quasar-kotlin-0.7.2.jar!\co\paralleluniverse\kotlin\Actor.class: (-1, -1) Class 'co/paralleluniverse/kotlin/Actor' was compiled with an incompatible version of Kotlin. Its ABI version is 0.23.0, expected ABI version is 0.25.0
[ERROR] E:\maven_local_repositories\co\paralleluniverse\quasar-kotlin\0.7.2\quasar-kotlin-0.7.2.jar!\co\paralleluniverse\kotlin\KotlinPackage.class: (-1, -1) Class 'co/paralleluniverse/kotlin/KotlinPackage' was compiled with an incompatible version of Kotlin. Its ABI version is 0.23.0, expected ABI version is 0.25.0
```

My pom config like:

```xml
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-stdlib</artifactId>
    </dependency>
    <dependency>
      <groupId>org.jetbrains.kotlin</groupId>
      <artifactId>kotlin-reflect</artifactId>
    </dependency>
    <dependency>
      <groupId>co.paralleluniverse</groupId>
      <artifactId>quasar-kotlin</artifactId>
      <version>${quasar.version}</version>
      <exclusions>
        <exclusion>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-stdlib</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.jetbrains.kotlin</groupId>
          <artifactId>kotlin-reflect</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```
Do this give any help?

**Comment by circlespainter** [comment]
@beihaifeiwu Well this means that Kotlin M13 is not binary-compatible with Kotlin M12. Going to look into the changes needed soon.

**Comment by circlespainter** [comment]
Closing with https://github.com/puniverse/quasar/commit/1803d7963ccaaacfe2e5129ec7ea8d2f0a8915d0.

Sonatype Snapshot now has a `0.7.4-SNASPHOT` with Kotlin M13 support.
