### ISSUE TITLE
Actor.trySend returns true if Actor is dead

### ISSUE THREAD

**Issue by hsestupin** [puniverse/quasar#126]
Is it an expected behaviour? https://github.com/puniverse/quasar/blob/master/quasar-actors/src/main/java/co/paralleluniverse/actors/Actor.java#L447

**Comment by pron** [comment]
Yes. As in Erlang, sends to a dead actor always succeed (but are silently dropped), so `trySend` must return `true`.

**Comment by hsestupin** [comment]
Thanks!
