### ISSUE TITLE
DisruptorReceiveChannel

### ISSUE THREAD

**Issue by SercanKaraoglu** [puniverse/quasar#135]
Hi,
I am wondering if I can use fibers instead of threads on disruptor ring buffer. I've noticed that in quasar-core there is class called DisruptorReceiveChannel but I am not able to extend it for implementing new channel. when I try to initialize it, It is giving me this error: 
Exception in thread "main" java.lang.AssertionError: java.lang.NoSuchFieldException: sequencer
    at co.paralleluniverse.strands.channels.disruptor.NewDisruptorReceiveChannel.<clinit>(NewDisruptorReceiveChannel.java:169)

I saw that it uses reflection api to reach the sequencer field, currently in disruptor 3.3.2 RingBuffer extends RingBufferFields so it causes that error. What would be proper way to use disruptor receive channel

**Comment by pron** [comment]
That disruptor code in Quasar was always experimental and unsupported, and we haven't maintained it due to lack of interest. If you'd like to contribute a PR we'll gladly accept it.

**Comment by SercanKaraoglu** [comment]
I think using disruptor's ring buffer instead of bounded queue can benefit on performance of producer consumer pattern. I am willing to contribute on this. 
Thanks

**Comment by pron** [comment]
Oh, you mean using a disruptor internally as a channel implementation hidden from the user or adding support for a fiber disruptor consumer? 

The current Quasar queues use the exact same algorithms used by the disruptor (which are the standard multithreaded queue algorithms). The disruptor is just a simple lock-free array-based queue. Its contribution and novelty is in the handling of multiple concurrent consumers and managing dependencies among consumers, features that channels don't support anyway.

**Comment by SercanKaraoglu** [comment]
Actually I was thinking to do both. "using a disruptor internally as a channel implementation hidden from the user" would be good starting point, after that I would be warmed up and can try to add support for fiber disruptor consumer. And then I want to do the something like this
https://github.com/LMAX-Exchange/disruptor/wiki/Performance-Results
but with millions of consumer Just curiosity

**Comment by SercanKaraoglu** [comment]
One usage area I am thinking would be, say we have real time market data and want to log, replicate and journal it first, then want to do 1000 calculations.

**Comment by pron** [comment]
Well, as I said, there’s no point in using a disruptor internally as a channel implementation, as a disruptor is no different from any array-based multiple-producer queue (the algorithms are identical). The disruptor’s contributions are relevant only when multiple consumers are involved and/or a chain of consumers. 

The goal of `DisruptorReceiveChannel` is to present a channel API for any single disruptor consumer: You have a disruptor and a consumer (probably one of many), and you want the consumer to use the channel API.  If it’s not working now and you’d like to fix it, that would be much appreciated.

**Comment by SercanKaraoglu** [comment]
Allright I am going to fix it
Thanks

**Comment by pron** [comment]
Cool. Thanks!

**Comment by SercanKaraoglu** [comment]
Hi @pron I have a little question, can I switch between FiberTasks, now I can only have one FiberTask per thread Thread doesn't take another task without finishing its current task. Isn't Fiber.yield() supposed to do this for me.

**Comment by SercanKaraoglu** [comment]
This is the example code that I used after fix and it works but please have a look at to StrandWaitStrategy is there another way rather than using Strand.parkNanos
```
final RingBuffer<IntEvent> buffer = RingBuffer.createSingleProducer(IntEvent.FACTORY, 1024, new StrandBlockingWaitStrategy());

        List<Fiber<Void>> list = IntStream.range(0, 100).mapToObj(i -> {
            final Fiber<Void> consumer = new Fiber<Void>("" + i, () -> {
                final DisruptorReceiveChannel<IntEvent> channel = new DisruptorReceiveChannel<IntEvent>(buffer, new Sequence[] {});
                while (!channel.isClosed()) {
                    final IntEvent event = channel.receive();
                    if (null != event)
                        System.out.println("thread id: "
                                           + Thread.currentThread().getId()
                                           + "fiber id: "
                                           + Fiber.currentFiber().getId()
                                           + " incoming: "
                                           + event.getValue());
                }
            });
            consumer.start();
            return consumer;
        }).collect(Collectors.toList());

        final Fiber<Void> producer = new Fiber<Void>("-1", () -> {
            for (int i = 0; i < 100; i++) {
                long sequence = buffer.next();
                try {
                    IntEvent e = buffer.get(sequence);
                    e.setValue(i);
                } finally {
                    buffer.publish(sequence);
                }
            }

        });
        producer.start().join();
        list.forEach(f -> {
            try {
                f.join();
            } catch (Exception e) {
                // TODO Auto-generated catch block
                e.printStackTrace();
            }
        });
        Thread.sleep(10000);

```

**Comment by pron** [comment]
> is there another way rather than using Strand.parkNanos

I don't understand. That is a blocking wait strategy, and that's how you block a strand. Why do you need something else?

**Comment by SercanKaraoglu** [comment]
Because I couldn't get it work with Strand.park() but Strand.parkNanos()

**Comment by pron** [comment]
What happened with `Strand.park`? If you have the agent running, it should work. Have you tried using Quasar with plain channels? Because playing with scheduling directly is advanced usage, and first we have to make sure that the basics work OK for you.

**Comment by SercanKaraoglu** [comment]
Oh sorry my fault I am not running the agent, By the way I tried using quasar with plain channels

**Comment by SercanKaraoglu** [comment]
After running agent it works 
Thanks
