### ISSUE TITLE
Kotlin support

### ISSUE THREAD

**Issue by winteryoung** [puniverse/quasar#143]
```kotlin
import co.paralleluniverse.fibers.Fiber
import co.paralleluniverse.fibers.Suspendable
import co.paralleluniverse.strands.Strand
import co.paralleluniverse.strands.SuspendableCallable
import java.util.*

fun main(args: Array<String>) {
    val senders = ArrayList<Fiber<*>>()
    for (i in 1..2) {
        val sender = fiber @Suspendable { // Here @Suspendable cannot be ignored, or the behaviour will be funny
            println("sender[$i] start")
            Strand.sleep(2000)
            println("sender[$i] end")
        }
        sender.start()
        senders.add(sender)
    }

    senders.forEach { it.join() }
}

fun <T> fiber(action: () -> T): Fiber<T> {
    return Fiber(SuspendableCallable @Suspendable {
        action()
    })
}
```

Like the comment said, I expect the annotation could be ignored. I cannot expect my team members to always remember to add that annotation. If for one time, we forgot to add that annotation, application wouldn't crash, it would behave in a strange way. Just run it, and you will know.

|LIB|VER|
|---|---|
| Kotlin | 1.0.0-beta-3595 |
| JDK | 8 |
|Quasar|0.7.3|

**Comment by circlespainter** [comment]
You can use [instrumentation verification](http://docs.paralleluniverse.co/quasar/#advanced-fibers) during development and it will report missing annotations.
You can also use `SuspendableScanner` (same docs section) to detect suspendable methods and call sites at build time.

Fully automatic instrumentation should be available in the future on Java 9+.

**Comment by Jire** [comment]
As a comment, if I recall correctly ParallelUniverse stated they are waiting on Java 9 for some needed features to support automating this.

**Comment by winteryoung** [comment]
OK. Thank you, guys.
