### ISSUE TITLE
Using ByteBuddy instead of ASM

### ISSUE THREAD

**Issue by pratikpparikh** [puniverse/quasar#144]
Has the quasar team looked a bytebuddy as an option rather then ASM for instrumentation?

ByteBuddy might be a way to solve manual annotation for marking suspend-able while we are waiting for Java9.

**Comment by pron** [comment]
As a matter of fact, [we use ByteBuddy](https://github.com/puniverse/quasar/blob/master/quasar-actors/src/main/java/co/paralleluniverse/actors/behaviors/ProxyServerActor.java#L288) where appropriate, but not for the "core" Quasar instrumentaton. ByteBuddy is a higher-level abstraction *on top* of ASM, and the core instrumentation is low-level, so using ByteBuddy would require using it's low-level features, which are basically just ASM. 

Besides, ASM is very convenient for this kind of work. ByteBuddy is great when you need to generate "boring" wrapper methods; when transforming existing methods in interesting ways, ASM is just at the right abstraction level.

**Comment by pratikpparikh** [comment]
Thanks, that helps.
