### ISSUE TITLE
Upgrade Kryo to latest version

### ISSUE THREAD

**Issue by mikehearn** [puniverse/quasar#145]
I use Kryo 3.0.3 in my app. Quasar uses Kryo 2. It'd be great if it could be upgraded to the latest version to avoid conflicts.

**Comment by pron** [comment]
Sure, but in the meantime, does it work if you do a manual exclusion or are there breaking changes in Kryo?

**Comment by mikehearn** [comment]
Seems it works. I can't run the Galaxy tests no matter what (it hangs on testPingPong) but the core and other module tests all work if I bump the version. I can get by with forcing things for now.

**Comment by pron** [comment]
Fixed in PR #148
