### ISSUE TITLE
fiber start the value Incorrect with sleep

### ISSUE THREAD

**Issue by gumeng** [puniverse/quasar#155]
run below code the value i incorrect. the value i always 0 .
private static FiberForkJoinScheduler scheduler =
      new FiberForkJoinScheduler("wode", Fiber.DEFAULT_STACK_SIZE);

Fiber fiberRun = new Fiber(scheduler, new SuspendableRunnable() {
      @Override
      public void run() throws SuspendExecution, InterruptedException {
        for (int i = 0; i < 5; i++) {
          Fiber.sleep(300, TimeUnit.MILLISECONDS);
          logger.info("runnable value:{}", i);
        }
      }
    }).start();

**Comment by pron** [comment]
Hi. Are you running the agent?

(Also, creating a scheduler is entirely optional, and unnecessary in this case).

**Comment by gumeng** [comment]
i had comment unnecessary code except  a org.slf4j.Logger. and run in main method. but the value always 0.  i run code with jdk7u80
maven config 
                <dependency>
			<groupId>co.paralleluniverse</groupId>
			<artifactId>quasar-core</artifactId>
			<version>0.7.4</version>
		</dependency>
code:
public static void main(String[] args) {
    // testFiber();
    FiberForkJoinScheduler scheduler = new FiberForkJoinScheduler("wode", Fiber.DEFAULT_STACK_SIZE);
    Fiber fiberRun = new Fiber(scheduler, new SuspendableRunnable() {
      @Override
      public void run() throws SuspendExecution, InterruptedException {
        for (int i = 0; i < 5; i++) {
          Fiber.sleep(300, TimeUnit.MILLISECONDS);
          logger.info("runnable value:{}", i);
        }
      }
    }).start();
  }

**Comment by pron** [comment]
You need to start the Quasar agent, as [the docs explain](http://docs.paralleluniverse.co/quasar/#instrumentation).

(Also, there's no need to create a scheduler.

``` java
new Fiber(() -> {
    for(int i; ....
}).start();
``` 
)

**Comment by circlespainter** [comment]
@gumeng Have you had a chance to check it again against pron's suggestion?
