### ISSUE TITLE
Aeron integration

### ISSUE THREAD

**Issue by unicomp21** [puniverse/quasar#157]
Is Aeron and SBE integration on the roadmap?

**Comment by pron** [comment]
What kind of integration do you have in mind? I am not very familiar with Aeron or SBE, but in general:

1. Integration is only necessary if the library's API is synchronous. Libraries with asynchronous APIs can be used with Quasar just as within any Java code.

2. If synchronous interaction with an asynchronous API is desired, this is usually trivially achieved with the `FiberAsync` class, according to the method explained [here](http://blog.paralleluniverse.co/2014/08/12/noasync/). If a library has no "official" synchronous API, then this approach is preferable to us suggesting our own synchronous APIs to various libraries.

3. Libraries that support the [Reactive Streams](https://github.com/reactive-streams/reactive-streams-jvm/blob/v1.0.0/README.md) specifications are automatically integrated with Quasar, which is fully RS-compliant. The streams are [automatically transformed into Quasar channels](http://blog.paralleluniverse.co/2015/06/25/reactive-streams/).

Generally, we provide Quasar integration modules (as part of [Comsat](http://docs.paralleluniverse.co/comsat/)) for libraries that are synchronous and generally complex (like JDBC, JAX-RS etc.). Simpler libraries can be very easily used with Quasar with either no work at all, or very little work (under a day). This work is probably better done by people more familiar with the libraries in question than us, so, we are happy to receive contribution of such integration modules to [Comsat](https://github.com/puniverse/comsat).

Having said that, we do add Comsat modules for popular libraries when there's sufficient demand.

**Comment by unicomp21** [comment]
Thanks Ron!
