### ISSUE TITLE
Kotlin 1.0

### ISSUE THREAD

**Issue by terrybleger** [puniverse/quasar#159]
Any plan to support Kotlin 1.0 RC?

**Comment by circlespainter** [comment]
Sure, should not be hard. I'll let you know when a snapshot is available for it.

**Comment by circlespainter** [comment]
It looks like 1.0 is out

**Comment by circlespainter** [comment]
A `0.7.5-SNAPSHOT` version of `quasar-kotlin` using Kotlin `1.0.0` should now be available on SonaType.
