### ISSUE TITLE
Allow custom @Suspendable annotations

### ISSUE THREAD

**Issue by stepancheg** [puniverse/quasar#161]
I have a library, which should not depend quasar-core, because quasar has too many dependencies, and most library users won't use it with quasar. However, library might be useful if instrumented by quasar.

For example, library might have a function like

```
Result executeQuerySynchronously(String query) {
    // call async code and join
}
```

and that function might need instrumentation if it is used with quasar. Quasar currently won't instrument that function, because it neight declare `throws SuspendExecution` nor has `@Suspendable` annotation.

There could be two solutions for that problems:

* put `@Suspendable` annotation into separate artifact that has no dependencies, and make `quasar-core` depend on that `quasar-core-annotations` artifact
* or allow definition of custom `@Suspendable` annotations

It might work like this:
* quasar agent loads all `META-INF/co.paralleluniverse.fibers.Suspendable` files from the classpath
* each file contains a fully qualified name of an annotation
* quasar agent uses those annotations long with `co.paralleluniverse.fibers.Suspendable` to decide which functions need to be instrumented

Somewhat similar mechanism is used in GWT: GWT has `GwtIncompatible` annotation to skip functions during compilation. And GWT uses any annotation in any package from any library if it short name is `GwtIncompatible`. So, for example, guava library has own [GwtIncompatible](http://docs.guava-libraries.googlecode.com/git/javadoc/com/google/common/annotations/GwtIncompatible.html) annotation, and GWT undestands that annotation.

**Comment by pron** [comment]
You can make Quasar a compile-time dependency. Annotation classes that are not found at runtime are ignored by the JVM, and so your clients won't need to have Quasar on the classpath even if Quasar annotations are present.

**Comment by stepancheg** [comment]
@pron well, that should work, although it is not always convenient (because of extra librarties need to be downloaded, and to be included in classpath of developers, because of limitations of build systems etc.)

**Comment by pron** [comment]
Quasar has so few runtime dependencies that this shouldn't matter (basically Guava, ASM, Kryo and HDR). In any event, if this actually proves a problem in practice, I'll reconsider. No reason to spend resources on what may well be a non-issue.

**Comment by stepancheg** [comment]
Would you accept a patch?

**Comment by pron** [comment]
Because this isn't an actual issue in practice at this time, just something that you fear might be a nuisance to someone (and it may not be a problem for anyone at all), I see no point in adding code or complicating it if there is no real requirement, so not at this time. But thank you for offering!

**Comment by stepancheg** [comment]
It is an issue in large mixed projects where different teams use different libraries, different approaches and solve different problems using shared libraries. Simply telling everyone "now we use quasar, deal with it" does not work.

OK, I got your point, hope you change your mind.

**Comment by pron** [comment]
> Simply telling everyone "now we use quasar, deal with it" does not work.

You have misunderstood me. Quasar does not need to be a runtime dependency even if your project makes use of Quasar annotations. The only "problem" is the download of a few small libraries when people want to build the project that uses Quasar annotations (but not any project depending on it). Those dependencies are compile time only, and are not transitive.

**Comment by pron** [comment]
I'm closing this issue for now. If this becomes a problem in practice, please re-open.
