### ISSUE TITLE
Instrument calls to CompletableFuture

### ISSUE THREAD

**Issue by stepancheg** [puniverse/quasar#162]
Currently fiber calls to `CompletableFuture.get()` are not instrumented, you need to use `AsyncCompletionStage.get()`.

My request is unconditionally instrument calls to `CompetableFuture.get()` (by simply replacing them with `AsyncCompletionStage.get()`).

It is needed for two reason:

* it makes code safer (it won't hang if someone acdidentally forgets to use `AsyncCompletionStage`)
* it makes instrumentation friendlier to libraries that do not need quasar dependency

This issue is related to #161.

**Comment by pron** [comment]
Currently, it is our policy never to unconditionally instrument JDK classes, but we'll consider.
If fiber code calls `CompetableFuture.get()` nothing should hang. At worst you'll get a runtime warning telling you a fiber has accidentally blocked its underlying kernel thread, the same as with any accidental kernel-thread blocking.

**Comment by stepancheg** [comment]
> At worst you'll get a runtime warning telling you a fiber has accidentally blocked its underlying kernel thread

Yes, and when the thread pool is exhausted, the program hangs.

> Currently, it is our policy never to unconditionally instrument JDK classes

Not classes themself, but _calls_ to those classes. Unlike locks and conditions, `CompletableFuture` is suitable for async code as is.

Anyway quasar could start with making such instrumentation configured at start-time, e. g. by placing something like `META-INF/co.paralleluniverse.fibers.properties` which may contatin a line

```
instrument.completableFuture=true
```

**Comment by pron** [comment]
This is no different from any other calls to thread-blocking code, and in any event, you'll get the warning with the exact call site. But we'll consider.

**Comment by stepancheg** [comment]
Acutally, it'd be perfect if quasar could transparently work with not just `java.util.concurrent.CompletableFuture`, but with any "listenable" futures, like `com.ning.http.client.ListenableFuture`, `io.netty.channel.ChannelFuture`, `com.google.common.util.concurrent.ListenableFuture` (to name a few) and similar objects.

Probably qusar could use something like plugin system. E. g.

```
class MyQuasarPlugin {
    @QuasarPlugin(for=ListenableFuture.class, method="get")
    static <R> R get(ListenableFuture<R> future) throws SustendExecution {
        ... proper implementaion of get for fibers
    }
}
```

So when quasar encounters a plugin like above, first it replaces all calls to `listenableFuture.get()` with `MyPlugin.get(listenableFuture)`, and then instruments that plugin.

**Comment by pron** [comment]
Well, Quasar already supports Guava's `ListenableFuture`, and we assume many libraries would switch to `CompletableFuture` eventually. In any case, we are always happy to get contributions for more Comsat integration modules.

**Comment by stepancheg** [comment]
Quasar supports `ListenableFuture` with `AsyncListenableFuture` which is needed to be called explicitly.

My point is that quasar could work with async libraries transparently, so proper code for blocking and fiber execution could be written transparently without compile-time dependency on quasar.

Speaking of Comsat, it could also gain from such plugin system.

**Comment by pron** [comment]
If we decide to automatically replace thread-blocking calls with fiber- (or, more precisely, strand-) blocking ones, we'll do it for all of them (that we know of). Again, I am not ruling this out, but so far it has been our policy not to do that, because we don't want to magically and mysteriously replace calls, even if it means some small extra work for the developer. We're very careful with automatic bytecode transformation, and the current instrumentation is as unintrusive as we could make it. We just add a few bytecodes to save and restore the stack and instruction pointer; none of the original bytecode is removed or replaced.

**Comment by pron** [comment]
I'm closing this issue. If we decide on "magical replacement" of blocking calls we'll probably do it for more cases than just futures. Anyway, this idea is always under consideration.
