### ISSUE TITLE
Possible problem with 'keyword parsing'

### ISSUE THREAD

**Issue by twicejr** [puniverse/quasar#170]
I don't know what happens exactly, but, I have got internet, everything on osmc works.
Quasar worked perfectly, until now, suddenly. Maybe after a apt-get update on OSMC?

The log looks very strange to me, because all providers are first too slow, and then all links are blocked by keywords, or so it seems.

Kick me in the head, or maybe this is really a bug of some kind, after messing with something?

http://paste.osmc.io/izugohayem
`

**Comment by twicejr** [comment]
21:45:20  58.174870 T:1512043504  NOTICE: [plugin.video.quasar] Requesting http://localhost:65251/movie/76341/links from ['plugin://plugin.video.quasar/movie/76341/links', '4', '']
	21:45:20  58.184509 T:1549788144  NOTICE: [plugin.video.quasar] Searching links for: 76341
	21:45:20  58.202839 T:1549788144  NOTICE: [plugin.video.quasar] Resolved 76341 to Mad Max: Fury Road
	21:45:20  58.210571 T:1549788144  NOTICE: [plugin.video.quasar] INFO  linkssearch  â–¶ processLinks     [0mResolving torrent files...
	21:45:36  74.527702 T:1503654896  NOTICE: [script.quasar.magnetdl-mc] http://magnetdl.com/m/mad-max-fury-road-2015/se/desc/
	21:45:38  76.354019 T:1463809008  NOTICE: [script.quasar.kickass-mc] http://kat.cr/usearch/mad%20max%20fury%20road%202015/?field=seeders&sorder=desc
	21:45:38  76.460533 T:1472197616  NOTICE: [script.quasar.torrentz-mc] https://torrentz.eu/search?f=mad+max+fury+road+2015
	21:45:38  76.486061 T:1549788144  NOTICE: [plugin.video.quasar] [GIN] 2016/03/10 - 20:45:38 |[97;42m 200 [0m|      77.968Âµs | ::1 |[97;46m  [0m POST    /callbacks/63205844
	21:45:38  76.500229 T:1480586224  NOTICE: [script.quasar.eztv-mc] <addinfourl at 1445890968 whose fp = <socket._fileobject object at 0x56257530>>
	21:45:39  76.939148 T:1503654896  NOTICE: [script.quasar.magnetdl-mc] Accepted Keywords: ['480p', 'HDTV', '720p', '1080p', '3D', 'TeleSync', ' TS ']
	21:45:39  76.939369 T:1503654896  NOTICE: [script.quasar.magnetdl-mc] Blocked Keywords: ['Trailer']
	21:45:39  76.939476 T:1503654896  NOTICE: [script.quasar.magnetdl-mc] min Size: 0.0 GB
	21:45:39  76.939568 T:1503654896  NOTICE: [script.quasar.magnetdl-mc] max Size: MAX
	21:45:40  78.255241 T:1549788144  NOTICE: [plugin.video.quasar] [33mWARN  AddonSearcher script.quasar.magnetdl-mc â–¶ call             [0mProvider script.quasar.magnetdl-mc was too slow. Ignored.
	21:45:40  78.262825 T:1549788144  NOTICE: [plugin.video.quasar] [33mWARN  AddonSearcher script.quasar.torrentz-mc â–¶ call             [0mProvider script.quasar.torrentz-mc was too slow. Ignored.
	21:45:40  78.274139 T:1472197616  NOTICE: [script.quasar.torrentz-mc] Accepted Keywords: ['480p', 'HDTV', '720p', '1080p', '3D', 'TeleSync', ' TS ']
	21:45:40  78.274368 T:1472197616  NOTICE: [script.quasar.torrentz-mc] Blocked Keywords: ['Trailer']
	21:45:40  78.274475 T:1472197616  NOTICE: [script.quasar.torrentz-mc] min Size: 0.0 GB
	21:45:40  78.274567 T:1472197616  NOTICE: [script.quasar.torrentz-mc] max Size: MAX
	21:45:40  78.356529 T:1549788144  NOTICE: [plugin.video.quasar] [33mWARN  AddonSearcher script.quasar.kickass-mc â–¶ call             [0mProvider script.quasar.kickass-mc was too slow. Ignored.
	21:45:40  78.357574 T:1549788144  NOTICE: [plugin.video.quasar] INFO  linkssearch  â–¶ processLinks     [0mReceived 0 links.
	21:45:41  78.799080 T:1958281776   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.quasar/movie/76341/links]
	21:45:41  78.846375 T:1549788144  NOTICE: [plugin.video.quasar] [GIN] 2016/03/10 - 20:45:40 |[97;42m 200 [0m| 20.316376371s | ::1 |[97;44m  [0m GET     /movie/76341/links
	21:45:41  78.989342 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 French Bdrip Xvid Glups Avi ***Blocked File by Keyword***
	21:45:41  78.994019 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 Bdrip Twi7Ter Dub ***Blocked File by Keyword***
	21:45:41  79.001862 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 Truefrench Md Webrip Xvid Zt Avi ***Blocked File by Keyword***
	21:45:41  79.005486 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 Hdrip Xvid Etrg ***Blocked File by Keyword***
	21:45:41  79.017807 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 French Bdrip X264 Pridehd Mkv ***Blocked File by Keyword***
	21:45:41  79.028984 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 Web Dlrip Avc H264 ***Blocked File by Keyword***
	21:45:41  79.033607 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 Hqcam Xvid Ac3 Cpg ***Blocked File by Keyword***
	21:45:41  79.049248 T:1503654896 WARNING: [script.quasar.magnetdl-mc] Mad Max Fury Road 2015 Bdrip Dual Audio Rus Eng ***Blocked File by Keyword***
	21:45:41  79.053078 T:1503654896  NOTICE: [script.quasar.magnetdl-mc] >>>>>>10 torrents sent to Quasar<<<<<<<

**Comment by pron** [comment]
Wrong [project](https://github.com/scakemyer/plugin.video.quasar).

**Comment by twicejr** [comment]
Ok, sorry
