### ISSUE TITLE
Monitored ProxyServerActors do not provide correct stats in MXBean

### ISSUE THREAD

**Issue by nickman** [puniverse/quasar#173]
Registered ActorMXBeans for monitored ProxyServerActor instances are not updated to show:

- QueueLength
- ReceivedMessages

although they do appear to reflect last restart cause and number of restarts. 
Originally discussed [here](https://groups.google.com/forum/m/?fromgroups#!topic/quasar-pulsar-user/aOBNFfV-n8U). I believe you already have a test case, but I can supply one if needed.

**Comment by circlespainter** [comment]
Thanks, a new `0.7.5-SNAPSHOT` containing the fix should now be available on SonaType.

**Comment by nickman** [comment]
Confirming. Works as expected.
Thanks.
