### ISSUE TITLE
Issue for FiberAsync.run(timeout, unit)

### ISSUE THREAD

**Issue by garretwu** [puniverse/quasar#175]
I suppose when we create a FiberAsync wrapper and pass timeout parameter to it, we should use new FiberAync.run(timeout, unit).

When we invoke the wrapper function in thread context, requestSync() should be invoked and "V" should be returned. Obviously according to following code, the return code is not what we expected.

It does not return after invoke runSync(timeout, unit), just return the getResult() which is null in this case.

public V run(final long timeout, final TimeUnit unit) throws E, SuspendExecution, InterruptedException, TimeoutException {
        if (Fiber.currentFiber() == null)
            **runSync(timeout, unit);**

**Comment by pron** [comment]
Thank you!
