### ISSUE TITLE
FiberScheduler is not subclassable by users

### ISSUE THREAD

**Issue by mikehearn** [puniverse/quasar#181]
I'd like to create a custom FiberScheduler that forbids the use of Strand.sleep (or converts it to a call to Thread.sleep), because I want precise control over the thread each fiber runs on (for now) and Strand.sleep will, by default, result in the fiber being suspended then resumed on a different thread. Which is fine for Quasar's intended use case in which fibers are scheduled by a big thread pool but as you know we're using it slightly differently.

Unfortunately FiberScheduler's constructor is package local, meaning I can't subclass it. It'd be nice if I could.

**Comment by pron** [comment]
Doesn't [`FiberExecutorScheduler`](http://docs.paralleluniverse.co/quasar/javadoc/co/paralleluniverse/fibers/FiberExecutorScheduler.html) give you enough control?

**Comment by mikehearn** [comment]
Not all the methods in it are public/protected.

**Comment by pron** [comment]
What do you need more than `execute` for precise thread control? We use it to schedule fibers on the AWT/Swing/JavaFX UI thread.

**Comment by mikehearn** [comment]
I'd like to throw UnsupportedOperationException if an attempt is made to use schedule rather than execute.

**Comment by pron** [comment]
OK, but I need to understand the usage better: `schedule` doesn't actually run the fiber on a separate thread: it just inserts an entry in a timer thread. Every time the fiber executes, it is guaranteed to go through `execute`, and you get to pick the thread it runs on.

**Comment by mikehearn** [comment]
Ah, that is a good point. I hadn't noticed that timer.schedule eventually ends up back at the scheduler's execute method. 

I used to just have a regular SameThreadExecutor because there was no specific executor for my control thread, but nowadays there is, so I can just replace my SameThreadScheduler with one that is more directly written and puts things back onto the right thread in execute. Thanks.
