### ISSUE TITLE
doc suggest "./gradlew", which is missing

### ISSUE THREAD

**Issue by rkiddy** [puniverse/quasar#189]
See http://docs.paralleluniverse.co/quasar/

It says:

Building Quasar

     Clone the repository:
          git clone git://github.com/puniverse/quasar.git quasar
     and run:
          ./gradlew

But:

     $ git clone https://github.com/puniverse/quasar.git
     $ cd quasar/
     $ ls ./gradlew
     ls: ./gradlew: No such file or directory

**Comment by pron** [comment]
Right, we removed `gradlew` a while ago. We need to fix the docs. To build Quasar, install Gradle, and just type `gradle` in the project's root directory.
