### ISSUE TITLE
Get the current running Fibers

### ISSUE THREAD

**Issue by jonhkr** [puniverse/quasar#190]
Hello,

Is there a way to get the current running fibers?
I have a use case where I need to gracefully shutdown the program, to do that I need to wait till all the fibers have died, can you point me out the best way to do this?

Thank you. Nice library by the way. 😄

**Comment by pron** [comment]
Hi, and thank you.
As there can be millions of fibers, maintaining a collection of all of them would add a non-negligible burden. As most fibers will be doing nothing but processing, gracefully shutting them down means little. You should keep track of those fibers that you know need graceful shutdown (like those writing to files), and shut them down like you would threads (using `Fiber.interrupt()`).

**Comment by jonhkr** [comment]
I was thinking here, I think that in my case I actually don't need to gracefully shutdown the fibers.
Just to give you more context, I'm using fibers to process requests in a web server. In this project when a server is set to shutdown state, it shouldn't accept new connections and wait till all current processing requests end.
So what I can do is simply set a delay which the main thread should wait before exiting. I think that would solve the problem in a simple way and would't be so expensive as having a collection of fibers.

**Comment by pron** [comment]
You don't need a collection of fibers to do that, only a count. For example, you could use a `Phaser` to wait until there are no remaining fibers. Each new fiber would call `Phaser.register()`, when it terminates it will call `Phaser.arrive()`, and when you shut down, the main thread can call `Phaser.awaitAdvance()` to wait for all remaining fibers to terminate (optionally with a timeout, so you don't wait forever in case something goes wrong).

**Comment by jonhkr** [comment]
Oh that would be much better, I'll definitely use your approach.
Thanks a lot :)
