### ISSUE TITLE
Async DNS Resolver

### ISSUE THREAD

**Issue by linkerlin** [puniverse/quasar#197]
Standard JRE use system's blocking gethostbyname() api to resolve hostname .
Does quasar has a plan to fiber dns-resolve?

P.S.
FiberUDPSocket is useful too.

**Comment by pron** [comment]
That is a very good idea! Do you know any good libraries that have an async DNS API that we can wrap as fiber-blocking?

**Comment by linkerlin** [comment]
I just written one .

**Comment by linkerlin** [comment]
@pron I have done. See PR #216 .

**Comment by victornoel** [comment]
FYI I think netty introduced some non-blocking DNS API not so long ago…
