### ISSUE TITLE
Make Channels API more closely mirror a BlockingQueue

### ISSUE THREAD

**Issue by voidstarstar** [puniverse/quasar#199]
There are many parallels between the [`BlockingQueue`](https://docs.oracle.com/javase/8/docs/api/java/util/concurrent/BlockingQueue.html) interface that is thread-blocking and the [`Channel`](http://docs.paralleluniverse.co/quasar/javadoc/co/paralleluniverse/strands/channels/Channel.html) interface that is fiber-blocking.  The closer that the Channels API is to the `BlockingQueue`, the easier it will be for users to transition.

It may be worth documenting the methods with similar meanings.  Overall the naming scheme for the Channels API is far more intuitive, in my opinion.

| `Channel` | `BlockingQueue` |
| ----- | ----- |
| `close(Throwable t)`, `close()`, `isClosed()` | A BlockingQueue does not intrinsically support any kind of "close" or "shutdown" operation to indicate that no more items will be added. The needs and usage of such features tend to be implementation-dependent. |
| `send(Message message)` | `put(E e)` |
| `send(Message message, long timeout, TimeUnit unit)`, `send(Message message, Timeout timeout)` | `offer(E e, long timeout, TimeUnit unit)` |
| `trySend(Message message)` | `offer(E e)` |
| `receive()` | `take()` |
| `receive(long timeout, TimeUnit unit)`, `receive(Timeout timeout)` | `poll(long timeout, TimeUnit unit)` |
| `tryReceive()` | `poll()` |

The `add()`, `remove()`, and `element()` variants are excluded as they throw exceptions, whereas with the Channels API, a `Channel` is created with an explicit `OverflowPolicy` so there is no need for separate methods.

There are a few shortcomings, however, that I would request be considered for improvement.  For example, there are no methods to inspect the state of the Channel without modifying it.  These methods would be analogous to `peek()`, `isEmpty()`, etc.

Also, the `drainTo()` methods are not present in the Channels API.  These are not necessarily required, as they are more of a convenience than a limitation, but they may still be worth considering and they are fairly straight forward.

```java
public int drainTo(Collection<? super Message> c) {
  int n = 0;
  Message m;
  while ( (m = tryReceive()) != null) {
    c.add(m);
    ++n;
  }
  return n;
}

public int drainTo(Collection<? super Message> c, int maxElements) {
  int n = 0;
  Message m;
  while (n < maxElements && (m = tryReceive()) != null) {
    c.add(m);
    ++n;
  }
  return n;
}
```

The `peek()` and `drainTo()` analogous methods, if created, would possibly find a home in [`ReceivePort`](http://docs.paralleluniverse.co/quasar/javadoc/co/paralleluniverse/strands/channels/ReceivePort.html) to be accessible from outside of the Channels API as well.

These are merely design decision suggestions and not critical issues, so feel free to reject this as a "will not fix".  This issue has relatively low importance.

**Comment by pron** [comment]
I think the best path is to create an adapter to wrap channels with the relevant queue methods. It's important to understand that channels and queues are not quite the same. Queues are more general-purpose and are a lower-level abstraction. Channels are higher-level, and have "application" semantics, like propagation of exceptions. But an adapter is certainly acceptable.

**Comment by voidstarstar** [comment]
I had not realized that the Channels API is intended to be a higher-level abstraction on top of a queue.  Thanks for the clarification.

I agree that a wrapper around a channel would work perfectly fine, but since queues are a lower-level abstraction, the wrapper may incur a performance penalty for certain methods.  For something like `drainTo()`, there would be no penalty.  For inspection methods such as `peek()`, on the other hand, since a channel has no way of viewing the elements without modifying the channel, it would be necessary to `tryRemove()` all elements and then `send()` them again.  This changes a potential `O(1)` operation into a `O(n)` one.

For my use case, I will be able to use a wrapper with a negligible performance hit in practice since my channel will only have a very small constant number of elements.  I'm fortunate that this is a non-issue for me, but in the general case I think it may lead to a performance issue when using a wrapper class.  Should this issue be closed since a wrapper can be used as a workaround?

**Comment by pron** [comment]
> For inspection methods such as `peek()`

Channels intentionally don't implement `peek()`. They are at core a concurrency mechanism, and `peek` is rather meaningless if there are multiple readers. Same goes for `isEmpty` etc.. I only meant those methods that have counterparts.

> Should this issue be closed since a wrapper can be used as a workaround?

It's not a workaround, but a reasonable solution, as channels are not the same kind of entity as j.u. queues. 

At first I thought that maybe we should provide a "standard" wrapper, but as it won't really implement the `Queue` interface, I don't think it should be part of Quasar code. Maybe we'll add such a wrapper at some future time, but for now I'm closing the issue.
