### ISSUE TITLE
[Kotlin] Fibers created with `fiber` have uninstrumented frames with AOT when not `@Suspendable`

### ISSUE THREAD

**Issue by bsideup** [puniverse/quasar#200]
Hi @pron !

I remember it was possible to call fibers without `@Suspendable`, but now I see it's mandatory. Is it possible somehow to avoid it? I'm developing the DSL and it's a bit ugly to add `@Suspendable` everywhere in human-readable DSL :(

Thanks!

**Comment by circlespainter** [comment]
Hi, yes some things have changed on the way to Kotlin 1.0. I'll have a look again and see if it's possible to have at least some DSL usages instrumented without `@Suspendable` and without significantly affecting performance.

Anyway, for JDK9+ most probably Quasar will support automatic instrumentation at the bytecode level so it'll work for all JVM languages and all libraries, plus annotating code will become optional.

**Comment by bsideup** [comment]
@circlespainter thanks for the response! 

BTW where I can track the status of JDK 9 support? Is there something going already?

**Comment by circlespainter** [comment]
Yes there is quite a lot and at present we're working with the OpenJDK guys to understand few things about the new `StackWalker` API. The Quasar branch is `jdk9`.

**Comment by bsideup** [comment]
@circlespainter that is great! Do you have some working examples in `jdk9` already?

**Comment by circlespainter** [comment]
The branch includes a partially working (also because of some `StackWalker` issues we're discussing) port of the fiber-related Quasar test suite without `throws SuspendExecution`, `@Suspendable` etc.

It's just regular Quasar without annotations anyway, there isn't much difference, just definitely more convenient because instrumentation can work fully automatically thanks to some new JDK9 features.

The status is very much "work in progress" though, e.g. very little performance work has been done untl now.

**Comment by bsideup** [comment]
ok, cool, will dig into it soon. No worries about the performance or bugs ATM, not planning to deploy it to production tomorrow :D But I definitely want to play with it already and maybe give some feedback or report issues

**Comment by circlespainter** [comment]
@bsideup Could you try removing `@Suspendable` from your `fiber` DSL usages with Quasar `0.7.6-SNAPSHOT` and run with instrumentation verification enabled (to make sure everything is OK)? In `quasar-kotlin` tests `@Suspendable` is not anymore necessary in those circumstances.

**Comment by bsideup** [comment]
@circlespainter sounds great, I definitely check a bit later today or tomorrow! Thanks!

**Comment by bsideup** [comment]
@circlespainter actually, I just figured out how to use them without an annotation with the latest **released** Quasar:

```java
public interface FiberCallable<V> extends SuspendableCallable<V> {
}

public class fiber<T> extends Fiber<T> {

    public fiber(FiberCallable <T> callable) {
        super(callable);
    }
}
```

`FiberCallable` should be marked as suspendable super class. 

Then:
```kotlin
fiber {
    Strand.sleep(100);
}
```

Thanks to Kotlin's SAM conventions, it'll generate something like:

```
new fiber(new AsyncCallable<Unit>() {
    public Unit run() throws SuspendExecution, InterruptedException {
        Strand.sleep(100);
    }
});
```

And Quasar will instrument it as usual.

**Comment by circlespainter** [comment]
Nice, I wonder why it doesn't work for Quasar's `fiber` as it's not doing something a lot different. Which Kotlin version are you using with `0.7.5`? Also, can you confirm it works without this workaround in `0.7.6-SNAPSHOT` from the tip of the `0.7.0` branch?

**Comment by bsideup** [comment]
@circlespainter nope, doesn't work with the latest `0.7.6-SNAPSHOT` built from `0.7.0` branch.

I might share a simple example project with my solution if you want :)

**Comment by circlespainter** [comment]
Sure, if you could, so I could have a look. Thanks

**Comment by bsideup** [comment]
@circlespainter 

Done:
https://github.com/bsideup/quasar-kotlin-without-annotations

Clone and run `./gradlew example:run`. `verifyInstrumentation` is set to `true` as well.

Built on top of the latest Quasar (0.7.5) and Kotlin (1.0.2)

**Comment by bsideup** [comment]
Of course this implementation is pretty ugly, has hardcoded interface name instead of a reference, etc, but the idea is pretty clear I think :)

**Comment by circlespainter** [comment]
I see you're using AoT. [This test](https://github.com/puniverse/quasar/blob/master/quasar-kotlin/src/test/kotlin/co/paralleluniverse/kotlin/fibers/FiberKotlinTest.kt#L28) does not specify `@Suspendable` and it works with the agent; the same holds true for your test but instead AoT instrumentation seems not to detect the `MainKt` classes and they don't get instrumented. I'll look further into it.

**Comment by bsideup** [comment]
@circlespainter cool, thanks :) 

BTW should I focus on the agent (because of JDK 9) or AOT will remain? 

I would strongly prefer to use AOT because of the specifics of my system where I have to run multiple JVMs for a short time, plus attaching Java agents to them adds complexity to the system as well

**Comment by circlespainter** [comment]
Currently there are no plans to give up AOT. Actually the instrumentation logic is shared by all methods (e.g. agent, AOT, classloaders), they are basically adapters and differ only in the way they call the instrumentor (and when).

I understand you don't want extra warmup time but as for the complexity there are ways to manage very easily a Java agent, see e.g. [Capsule](http://www.capsule.io/). Also consider that most people use the Java Agent as it's the most flexible method (for example it can instrument 3rd-party libs).

**Comment by bsideup** [comment]
Well, I work at ZeroTurnaround where everything we develop is a java agent :D I pretty realize the profit from it, but, unfortunatelly, my single, specific usecase forces me to use AOT as much as possible, but I have a room to fallback to the agent if AOT will not cover all my requirements. 

Thanks!

**Comment by circlespainter** [comment]
If you use a `0.7.6-SNAPSHOT` built from the tip of `0.7.0` you should now be able to make your example work without `@Suspendable` and without re-implementing `fiber`, both when using the agent and when using AOT.
