### ISSUE TITLE
Cannot setup all keep alive options for tcp socket

### ISSUE THREAD

**Issue by linkerlin** [puniverse/quasar#205]
Something like in C:
int keepalive = 1; 
int keepidle = 60; 
int keepinterval = 5; 
int keepcount = 3;
setsockopt(rs, SOL_SOCKET, SO_KEEPALIVE, (void *)&keepalive , sizeof(keepalive ));
setsockopt(rs, SOL_TCP, TCP_KEEPIDLE, (void*)&keepidle , sizeof(keepidle ));
setsockopt(rs, SOL_TCP, TCP_KEEPINTVL, (void *)&keepinterval , sizeof(keepinterval ));
setsockopt(rs, SOL_TCP, TCP_KEEPCNT, (void *)&keepcount , sizeof(keepcount ));

**Comment by circlespainter** [comment]
I think [this](http://stackoverflow.com/questions/22472844/how-to-set-socket-option-tcp-keepcnt-tcp-keepidle-tcp-keepintvl-in-java-or-n) can help but I don't get the reason why you posted your question here: what's the connection with Quasar?

**Comment by circlespainter** [comment]
@linkerlin Closing soon if not getting feedback (you can always reopen).

**Comment by linkerlin** [comment]
@circlespainter I'm writing a proxy for socks5 protocol. I want to know when a tcp-socket disconnected. But Quasar's FiberSocketChannel cannot set tcp-keep-alive option.

**Comment by circlespainter** [comment]
`AsyncFiberSocketChannel` and `AsyncFiberServerSocketChannel` implement the `setOption` call by delegating to [`AsynchronousSocketChannel.setOption()`](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/AsynchronousSocketChannel.html#setOption(java.net.SocketOption,%20T)) and [`AsynchronousServerSocketChannel.SetOption()`](https://docs.oracle.com/javase/7/docs/api/java/nio/channels/AsynchronousServerSocketChannel.html#setOption(java.net.SocketOption,%20T)) resp. Doesn't it work for you?
