### ISSUE TITLE
Dead link in doc.

### ISSUE THREAD

**Issue by linkerlin** [puniverse/quasar#222]
http://www.matthiasmann.de/content/view/24/26/
Acknowledgments
A core component of Quasar, bytecode instrumentation, is a fork of the wonderful **Continuations Library** by Matthias Mann.

The **Continuations Library** is very old library, is there a plan for rewriting one ?

**Comment by pron** [comment]
The original code was forked and very heavily modified. It's as good as new.

**Comment by linkerlin** [comment]
@pron Where can I find the repo?

**Comment by pron** [comment]
Everything is part of quasar-core, in the `co.paralleluniverse.fibers.instrument` package.
