### ISSUE TITLE
Should UnableToInstrumentException extend AnalyzerException?

### ISSUE THREAD

**Issue by roded** [puniverse/quasar#241]
Hi, 
I've encountered this with the jOOQ Comsat integration: the classifier does not filter out constructors.
It seems that `InstrumentClass.visitEnd()` is aborted by the thrown `UnableToInstrumentException` in case a "special method" is encountered, not giving the other methods a chance to be instrumented.
Is this intended?

**Comment by pron** [comment]
Well, how to recover from errors in instrumentation code is an interesting question, but I think that your suggestion is more consistent with what we do at the class level (we do not abort the program when we encounter an `UnableToInstrument`), so I'll fix this.
