### ISSUE TITLE
Fiber instantiation is incredibly slow

### ISSUE THREAD

**Issue by tinycedar** [puniverse/quasar#242]
Hi I am testing Quasar Fiber:

```
public static void main(String[] args) throws IOException {
        long past = System.currentTimeMillis();
        Fiber ff = new Fiber() {
            @Override
            protected Object run() throws SuspendExecution, InterruptedException {
                return null;
            }
        };
        System.out.printf("Costs %d ms\n", System.currentTimeMillis() - past);
    }
```

and the output:
```
Costs 458 ms
```

I am wondering of the Fiber instantiation slowness. Is it because of class instrumentation when loading Fiber class ?

**Comment by pron** [comment]
Please do a JMH benchmark. Your program's behavior may be a result of many things that have nothing to do with Quasar. For example: the JVM is free not to construct fibers at all, as they are not used. OTOH, a loop in main requires on-stack replacement for optimizations. The *only* way to measure performance on the JVM is with JMH.
