### ISSUE TITLE
Feature request: list all registered actors

### ISSUE THREAD

**Issue by ov7a** [puniverse/quasar#252]
Subj. I would be nice to have a method (probably in ActorRegistry) to list ids of all registered actors. E.g. for monitoring purposes.

**Comment by pron** [comment]
Hi.
This information is already provided and available via JMX. See [ActorsMXBean](https://github.com/puniverse/quasar/blob/master/quasar-actors/src/main/java/co/paralleluniverse/actors/ActorsMXBean.java), and [ActorMXBean](https://github.com/puniverse/quasar/blob/master/quasar-actors/src/main/java/co/paralleluniverse/actors/ActorMXBean.java). A registered actor is automatically monitored.

**Comment by circlespainter** [comment]
@ov7a Is that what you needed?

**Comment by ov7a** [comment]
Could you provide MWE, please?

**Comment by ov7a** [comment]
Hmm, maybe I'm doing something wrong, but these are interfaces. The only implementation of ActorsMXBean  is JMXActorsMonitor, which is package-private. Could you please provide a minimum working example?

**Comment by pron** [comment]
`ActorsMXBean` is an MBean with the name `"co.paralleluniverse:type=Actors"`. It can be accessed locally (i.e. in the same JVM) with:

``` java
ActorsMXBean proxy =
    ManagementFactory.newPlatformMXBeanProxy(ManagementFactory.getPlatformMBeanServer(),
                                             "co.paralleluniverse:type=Actors",
                                             ActorsMXBean.class);
```

See http://docs.oracle.com/javase/8/docs/technotes/guides/management/mxbeans.html
