### ISSUE TITLE
RequestReplyHelper checked vs unchecked exceptions

### ISSUE THREAD

**Issue by roded** [puniverse/quasar#260]
`RequestReplyHelper.call` propagates checked and unchecked exceptions differently.
By its use of `Exceptions.rethrow`,  checked exceptions are wrapped with a `RuntimeException` while `RuntimeException`s are re-thrown as is.
This should be documented here: http://docs.paralleluniverse.co/quasar/#behaviors

**Comment by pron** [comment]
It's a low-level detail that's documented in the Javadoc.
