### ISSUE TITLE
Why is @Suspendable not @Inherited?

### ISSUE THREAD

**Issue by mikehearn** [puniverse/quasar#276]
One of the most common cases where I forgot to mark methods as suspendable is when I've overridden a method that was already marked. If the annotation was meta-annotated with `@Inherited` that issue would seem to go away.

**Comment by pron** [comment]
Unfortunately, [`@Inherited` applies only to class annotations](http://docs.oracle.com/javase/8/docs/api/java/lang/annotation/Inherited.html): 

> Note that this meta-annotation type has no effect if the annotated type is used to annotate anything other than a class.
