### ISSUE TITLE
Quasar now works in JDK 11

### ISSUE THREAD

**Issue by doctorpangloss** [puniverse/quasar#305]
**Update**: This legend got quasar-core working up to JDK 11:

https://github.com/FroMage/quasi

Thanks @FroMage

**Original**:

It would seem that we're best off starting to transition to an alternative coroutines library. I don't think there's any activity for Quasar for a while, and the JDK9 branch was abandoned two years ago.

Since this will probably be the top issue for a while, we should use this discussion for alternatives. I certainly don't have the skills to maintain something as complex as a coroutines library.

After a quick search online, it would appear that Kotlin has coroutines that work for Java 9. Is this the path forward?

**Comment by kimec** [comment]
My understanding is that Ron is currently busy working for/with Oracle on project Loom which should bring "native" Fiber/lightweight continuation support directly into JVM without the need of auxiliary library like Quasar:
http://cr.openjdk.java.net/~rpressler/loom/Loom-Proposal.html
https://www.youtube.com/watch?v=fpyub8fbrVE
http://openjdk.java.net/projects/loom/

I've read somewhere that some Loom preview of some sort should be released in JDK10. [JDK10 is to be released later this month](http://openjdk.java.net/projects/jdk/10/).

Also, I may be wrong here, but I think JetBrains developed Kotlin coroutines with some guidance/support from Ron.

**Comment by doctorpangloss** [comment]
That sounds really good, I hope Loom works well.

**Comment by george-hawkins** [comment]
It'd be nice if it at least built in it's own CI environment even if it's not being very actively updated.

The last commit by @pron resulted in the build breaking - but not for reasons that seem to have anything to do with the code changes introduced.

If you look at the Travis CI [log output](https://travis-ci.org/puniverse/quasar/jobs/334497868) you see:

```
ERROR: JAVA_HOME is set to an invalid directory: /usr/lib/jvm/java-7-oracle
Please set the JAVA_HOME variable in your environment to match the location of your Java installation.
```

I'm guessing (wildly) that Java 7 no longer exists on the CI environment and that `JAVA_HOME` just needs to be updated to point to Java 8?

**Comment by yanxinyuan** [comment]
Coroutines is good. but untill now, it seems we can't introduce it to production environment. Sad

**Comment by HellScre4m** [comment]
Excuse me, I know this is completely irrelevant, but I'm damn surprised to use Project Loom in a demo project I intend to deploy later, but sadly I can't build openjdk on windows :( It's due to space in VC path which is not my choice (VS and its bullshit directory standards), can you help me in any way or just refer me to somewhere where I can get help? openjdk mailing lists don't care and I'm paralyzed.

**Comment by kimec** [comment]
Project Loom initial prototype announced/released today http://mail.openjdk.java.net/pipermail/loom-dev/2018-July/000062.html

**Comment by FroMage** [comment]
> Update: This legend got quasar-core working up to JDK 11:

To clarify: yes I got quasar-core, but I had to drop all the other modules, and I did not test it in module-path mode. It does work in classpath-mode, however.

**Comment by doctorpangloss** [comment]
There is now official JDK 11 support.
