### ISSUE TITLE
timing issues in self-cancellation test

### ISSUE THREAD

**Issue by dehubbed** [puniverse/quasar#79]
I'm running the following test against quasar 0.6.3. SNAPSHOT (through pulsar 0.6.3. SNAPSHOT).
```
(ns self-cancellation
  (:use [co.paralleluniverse.pulsar.core :only [spawn-fiber]])
  (:import co.paralleluniverse.strands.Strand))

(defn cancel-test []
  (spawn-fiber
	  (fn []
	    (try
	      (let [current (Strand/currentStrand)]
	        (spawn-fiber
	          #(do
	             (Strand/sleep 250)
	             (future-cancel current))))
	      (Strand/sleep 500)
	      (println "ok")
	      (catch Exception ex (.printStackTrace ex))))))
```

What *should* happen is that every time `cancel-test` runs, it prints an `InterruptedException` stack trace, correct?

When I run `(cancel-test)` several times in a plain `lein repl`, e.g. 10 times, sometimes it produces that `InterruptedException`, but most times it doesn't. Can you reproduce that? Since apparently subtle timing issues are involved the exact setup (OS, CPU, etc.) may influence the outcome.

**Comment by pron** [comment]
If you call `(.interrupt current)` instead of `(future-cancel current)` you get the exception every time. Cancellation does something different, as it doesn't just interrupt the fiber, but cancels its underlying task. Since the task is cancelled, the fiber doesn't ever wake up to figure out it's been interrupted.

It might indeed make sense to make `future-cancel` behave just like `.interrupt` (can you think of a reason not to?)

**Comment by pron** [comment]
Thanks for catching this! 
Otherwise, canceling a fiber this way would have been very confusing!

**Comment by dehubbed** [comment]
Thanks. Fibers want to be a drop-in replacement for Java/Clojure futures so have to behave exactly the same, so it's not just about being confusing.
What about separate `(fiber)` & `(start)` commands, applying `(future-cancel)` to an unstarted fiber, then starting it? There isn't really an equivalent case in Java/Clojure. Not that I use this variant but it exists.

**Comment by pron** [comment]
You can do that by using the Java API directly. Do you think a Clojure API is necessary? Even threads don't have a Clojure API.

**Comment by dehubbed** [comment]
Uh maybe there is a misunderstanding. I'm just saying someone could write:
```
(def f (fiber))
(future-cancel f)
(start f)
```

Have you considered what you want the outcome of this to be and is this what you get now with the new future-cancel. There isn't really an equivalent in Clojure or Java. I for one don't care but you asked me to comment. :-)
