### ISSUE TITLE
Fiber class com.ailk.TestQuasar$1 has not been instrumented.

### ISSUE THREAD

**Issue by GeekTemo** [puniverse/quasar#89]
I write a sample.but when i run it.

QUASAR WARNING: Quasar Java Agent isn't running. If you're using another instrumentation method you can ignore this message; otherwise, please refer to the Getting Started section in the Quasar documentation.
Exception in thread "main" java.lang.IllegalArgumentException: Fiber class com.ailk.TestQuasar$1 has not been instrumented.

**Comment by pron** [comment]
Are you [running the agent](http://docs.paralleluniverse.co/quasar/#instrumentation)?

**Comment by pron** [comment]
Problem solved?

**Comment by stanlyjohn2** [comment]
i m having a similar error how to solve that?

**Comment by pron** [comment]
Are you [running the agent](http://docs.paralleluniverse.co/quasar/#instrumentation)?

**Comment by stanlyjohn2** [comment]
i just need to add "-javaagent:path to quasar-core jar" in the vm arguments in eclipse run configuration rite?

**Comment by pron** [comment]
Yes. (with the actual path, though :))

**Comment by stanlyjohn2** [comment]
thanx for the quick reply...:)..But i m still getting the same error.
java.lang.IllegalArgumentException: Fiber class com.webQ.controller.BaseController$GetFiber has not been instrumented.
	co.paralleluniverse.fibers.Fiber.<init>(Fiber.java:178)
	co.paralleluniverse.fibers.Fiber.<init>(Fiber.java:217)
	co.paralleluniverse.fibers.Fiber.<init>(Fiber.java:498)
	com.webQ.controller.BaseController$GetFiber.<init>(BaseController.java:76)
	com.webQ.controller.BaseController.getIt(BaseController.java:127)


i also have a doubt . this fiber class i can use similar to threads rite...
for example :- class getfiber extends fiber {
}
and then overriding the run method inside that?

**Comment by circlespainter** [comment]
Can you provide the relevant source code? How exactly are you running it in Eclipse, is it an imported project or just a main class with an Eclipse run configuration?

**Comment by stanlyjohn2** [comment]
it is a project ..actually a web application ..so no main class is there...i m running the application on a tomcat server..

The code is like this:-
@Controller
public class BaseController {

static class GetFiber extends Fiber  {

		HttpGet request = new HttpGet(some url);
				@Override
				protected Void run() throws SuspendExecution, InterruptedException {
					try {
						final CloseableHttpAsyncClient client  =FiberCloseableHttpAsyncClient.wrap(HttpAsyncClients.custom().
								setMaxConnPerRoute(1).setMaxConnTotal(1).build());
						client.start();
						
						Future<HttpResponse> future = client.execute(request, null);
						 HttpResponse response1 = future.get();
						    System.out.println(request.getRequestLine() + "->"        +  response1.getStatusLine());
						
					} catch (Exception ex) {
						System.out.println(ex.getLocalizedMessage());
					}
					return null;
				}

	}

	// Fiber code
	@RequestMapping(value = "/async", method = RequestMethod.GET)
	public String getIt() throws InterruptedException, SuspendExecution,
			ExecutionException, ParseException, IOException {

		GetFiber[] fibers=new GetFiber[10];
		for(int i=0;i<fibers.length;i++){
			fibers[i].start();
		}
}



I m new to this fiber.so can u check the flow of this program.?

**Comment by circlespainter** [comment]
I see, so you're using Spring and Tomcat.

Quasar can't (yet) make 3rd-party libraries automatically suspendable so that they can work with fibers. For this reason, [Comsat](http://docs.paralleluniverse.co/comsat/) provides several integration modules with popular/standard technologies such as Spring and also an instrumenting classloader that you need to use instead of the agent when running your application on a standalone Tomcat server. There are also [gradle](https://github.com/puniverse/comsat-gradle-template) and [maven](https://github.com/puniverse/quasar-gradle-archetype) templates that will show you how to setup the Tomcat instrumenting classloader with a Tomcat standalone server.

Please refer to the docs (mostly [here for the loader](http://docs.paralleluniverse.co/comsat/#enabling-comsat) and [here for Spring](http://docs.paralleluniverse.co/comsat/#spring)) for further information about how to use them and of course we'll be glad to help you in the forums for any help you may need.

**Comment by circlespainter** [comment]
Also, shouldn't you fill with newly created fibers the array you instantiated with `new GetFiber[10]` before attempting to access its elements in `fibers[i].start()`?

**Comment by stanlyjohn2** [comment]
Thanx for the reply ..i configured with spring and tomcat class loader from the above links u specified...
Now while running the webapp i am not geting any result..i am assuming there is some mistake in context.xml file .can u have a look.?
<?xml version="1.0" encoding="UTF-8"?>
<Context docBase="/home/webq/mtp/LoadGenerator" antiJARLocking="true" path="" reloadable="true">
 <Loader loaderClass="co.paralleluniverse.comsat.tomcat.QuasarWebAppClassLoader" />
 </Context>

**Comment by circlespainter** [comment]
I think your formatting has been lost. [This](https://github.com/puniverse/comsat-mvn-archetype/blob/master/src/main/resources/archetype-resources/src/main/webapp/META-INF/context.xml) is a working `context.xml` from the archetype, if you don't need the DB just remove the `ResourceLink` and `Resouce` elements.

What's the output of your whole execution? Can you share more of the project (or even the whole project if it's small and it is possible)?

**Comment by stanlyjohn2** [comment]
i solved the context.xml issue..now i am getting the homepage perfectly,which is a jsp file..but i am not able to access the pages defined in my controller class.. i am trying to use spring mvc ..for that i added
@Import(FiberWebMvcConfigurationSupport.class)
public class MyClass {
	
	@RequestMapping(value = "/hello", method = RequestMethod.GET)
	@ResponseBody
	public String hello() throws SuspendExecution, InterruptedException {
	System.out.println("doneeeeeeeeeeeeeeeeeeeeeee");
		for(int i=0;i<10;++i){
		Fiber<Void> f1 = new Fiber<Void>(() -> {
			 
			 Fiber.sleep(10);
			  System.out.println(Fiber.currentFiber().getName() + "done");
			 
			  }).start();
		}
}

since I are using the fiberwebmvcconfiguration,should i also need to define a spring dispatchercontext file also.? and i dont need to add the @Controller annotation right?

**Comment by stanlyjohn2** [comment]
i am getting the following error..what to do?
java.lang.linkage error :loader constraint violation :

**Comment by circlespainter** [comment]
[Here](https://github.com/circlespainter/spring4-mvc-gradle-annotation-hello-world) you can now find the Comsat port of a complete example "Hello World" project built with Spring MVC controller (with annotations) + Tomcat standalone servlet container (deployed and run with Cargo) + Gradle. It uses Comsat's instrumenting classloader for Tomcat.

You need to remove the `@EnableWebMVC` annotation from your Spring configuration class and add the `@Import(FiberWebMvcConfigurationSupport.class)` annotation.

Linkage errors usually are caused by version clashes between dependencies, I suggest you always force manual version conflict resolution as it is done in the above example project.

**Comment by stanlyjohn2** [comment]
I have done the above example. i am getting the homepage. but when i try to run the function with "/hello/{name}" request url i am getting the following error.
[quasar] ERROR: Unable to instrument class co/paralleluniverse/fibers
co.paralleluniverse.fibers.instrument.UnableToInstrumentException: Unable to instrument co/paralleluniverse/fibers/Fiber#onResume()V because of catch for SuspendExecution

My context.xml file is same as in the above example with tomcat class loader included. and i added the "comsat-tomcat-loader-0.4.0-jdk8.jar" in the "tomcat/lib" directory . still i am getting the instrument error

**Comment by stanlyjohn2** [comment]
Hey this the git repo of my project with the above example....
https://github.com/stanlyjohn2/LoadGenerator

just have a look

**Comment by circlespainter** [comment]
Don't worry about that error, we'll look into it but it's harmless (I get it as well). The page served by fiber controller methods is being rendered fine?

**Comment by stanlyjohn2** [comment]
i m not getting page served by fiber..when i run that page i m gettting the instrument error as I mentioned above..the below function is the page i am trying to access.this is from the example you specified..

@RequestMapping(value = "/hello/{name:.+}", method = RequestMethod.GET)
public ModelAndView hello(@PathVariable("name") String name) throws SuspendExecution, InterruptedException {
Fiber.sleep(10);
logger.debug("hello() is executed - $name {}", name);
ModelAndView model = new ModelAndView();
model.setViewName("index");
model.addObject("title", helloWorldService.getTitle(name));
model.addObject("msg", helloWorldService.getDesc());
return model;
}

**Comment by circlespainter** [comment]
Have a look at https://github.com/stanlyjohn2/LoadGenerator/pull/1 (ignore the instrumentation error).

Notes about how to run it in `README.md`.

**Comment by stanlyjohn2** [comment]
Thanx a lot fot the help..I got the output when running maven.Hope i can run this in eclipse also.

**Comment by circlespainter** [comment]
Yes for sure, it's just a matter of configuring it so that it does the same things that maven does. Not an expert though, so can't help you much there.

**Comment by stanlyjohn2** [comment]
for (int i = 0; i < 10; ++i) {
        Fiber<Void> f1 = new Fiber<Void>(() -> {
    		try {
				String url = "http://www.google.com/search?q=httpClient";
			 
			HttpClient client = HttpClientBuilder.create().build();
			HttpGet req = new HttpGet(url);
		 
			// add request header
			//request.addHeader("User-Agent", USER_AGENT);
			HttpResponse response;
			
				response = client.execute(req);
			
			System.out.println("Response Code : " 
		             + response.getStatusLine().getStatusCode());
			} catch (Exception e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
          
        }).start();

This is a code that I am running . i am gettig the respoonse code as the output. but it showing the following error also..what may be the reason?

[INFO] [talledLocalContainer] Response Code : 200
[WARNING] [talledLocalContainer] WARNING: fiber Fiber@10000009:fiber-10000009[task: ParkableForkJoinTask@4d68d976(Fiber@10000009), target: co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable@4171fa7a, scheduler: co.paralleluniverse.fibers.FiberForkJoinScheduler@4ad9384b] is hogging the CPU or blocking a thread.

**Comment by circlespainter** [comment]
Have a look at "Runaway Fibers" [here](http://docs.paralleluniverse.co/quasar/#fibers).

In your case maybe you're using the original Apache HTTP Client inside fibers, which blocks threads, while you should use instead [Comsat's](http://docs.paralleluniverse.co/comsat/#http-clients), which integrates Apache HTTP Client with Quasar and runs on fibers without blocking threads.

**Comment by stanlyjohn2** [comment]
I tried to make the comsat http client and got the result..but i didn't understand the setmaxconnperroute and setmaxconntotal in the following statement.can u breifly tell what it is.

final CloseableHttpAsyncClient client = FiberCloseableHttpAsyncClient.wrap(HttpAsyncClients.
        custom().
        setMaxConnPerRoute(concurrencyLevel).
        setMaxConnTotal(concurrencyLevel).
        build());
client.start();

**Comment by circlespainter** [comment]
That is part of the Apache HTTP Async Client API. You can find more information for example [here](https://hc.apache.org/httpcomponents-asyncclient-dev/httpasyncclient/apidocs/org/apache/http/impl/nio/client/HttpAsyncClientBuilder.html#setMaxConnPerRoute(int)) and [here](https://hc.apache.org/httpcomponents-client-ga/tutorial/html/connmgmt.html).

**Comment by stanlyjohn2** [comment]
Thanx for the reply..

**Comment by stanlyjohn2** [comment]
hey is there anything in fibers by which I can control the rate at which http requests are sent.(ie; a rate limiter for http requests).I have found "rate limiter from guava". But if i use that along with fibers it is causing issues as  its implementation is based on thread blocking.

**Comment by circlespainter** [comment]
I don't know of any specifically but solutions working with frameworks for which a Comsat integration exists have chances to work. You could try https://github.com/nlap/dropwizard-ratelimit and some ideas can also be found [here](http://stackoverflow.com/questions/29927984/throttling-a-rest-api-in-java). Something for servlets with async mode support could work too.

**Comment by stanlyjohn2** [comment]
Hey I have one doubt. i am running my project using the maven command " mvn -Ptomcat8x dependency:properties package cargo:run"  .. it is working fine..but if i modify some static content like some modification in the webpage,why i need to run the command again...static file modifications should be automatically updated rite?

**Comment by circlespainter** [comment]
No, I think the cargo plugin deploys a new .war file built from your sources. This means that if you update the latter, the modifications you made are not brought automatically into the war file (and re-deployed). Auto-update mechanisms for Maven may exist though.

**Comment by stanlyjohn2** [comment]
Hey, i am using the google ratelimiter in my program which uses fibers..it is working fine...but it is generating the following warning...Is it an issue? how can I disable these warnings...?

[WARNING] [talledLocalContainer] WARNING: fiber Fiber@10000014:fiber-10000014[task: ParkableForkJoinTask@39eb1921(Fiber@10000014), target: co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable@625bc7ff, scheduler: co.paralleluniverse.fibers.FiberForkJoinScheduler@398f884] is blocking a thread (Thread[ForkJoinPool-default-fiber-pool-worker-50,5,main]).
[INFO] [talledLocalContainer] 	at java.lang.Thread.sleep(Native Method)
[INFO] [talledLocalContainer] 	at java.lang.Thread.sleep(Thread.java:340)
[INFO] [talledLocalContainer] 	at java.util.concurrent.TimeUnit.sleep(TimeUnit.java:386)
[INFO] [talledLocalContainer] 	at com.google.common.util.concurrent.Uninterruptibles.sleepUninterruptibly(Uninterruptibles.java:275)
[INFO] [talledLocalContainer] 	at com.google.common.util.concurrent.RateLimiter$SleepingStopwatch$1.sleepMicrosUninterruptibly(RateLimiter.java:424)
[INFO] [talledLocalContainer] 	at com.google.common.util.concurrent.RateLimiter.acquire(RateLimiter.java:274)
[INFO] [talledLocalContainer] 	at com.google.common.util.concurrent.RateLimiter.acquire(RateLimiter.java:260)
[INFO] [talledLocalContainer] 	at com.webQ.model.TestPlan.execute(TestPlan.java:250)
[INFO] [talledLocalContainer] 	at com.webQ.controller.MainController.lambda$0(MainController.java:336)
[INFO] [talledLocalContainer] 	at com.webQ.controller.MainController$$Lambda$8/1449779630.run(Unknown Source)
[INFO] [talledLocalContainer] 	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:44)
[INFO] [talledLocalContainer] 	at co.paralleluniverse.strands.SuspendableUtils$VoidSuspendableCallable.run(SuspendableUtils.java:32)
[INFO] [talledLocalContainer] 	at co.paralleluniverse.fibers.Fiber.run(Fiber.java:1019)

**Comment by circlespainter** [comment]
The "Runaway Fibers" subsection in the ["Fibers" section of the docs](http://docs.paralleluniverse.co/quasar/#fibers) can help you with that.

**Comment by stanlyjohn2** [comment]
Thanks...Also i happened to go through the Photon project by puniverse to generate thousands of http requests....I ran the project and when I tried to generate more than 4000 reqs/second it is throwing exception telling that IO reactor stopped..anything less than 4000 reqs /sec it is working fine. why is it so?

**Comment by circlespainter** [comment]
Also you should get the reactor shutdown cause upon program termination if you're using Photon master. What does it say?

Usually the OS needs tuning in order to support several many open I/O descriptors at the same time, for example see [here](https://github.com/ptaoussanis/clojure-web-server-benchmarks/blob/master/scripts/tune-os.sh). Is tuning already applied?
