### ISSUE TITLE
question regarding byte code generation ..

### ISSUE THREAD

**Issue by RuedigerMoeller** [puniverse/quasar#98]
Hi, I am considering using quasar as an optional execution strategy for kontraktor distributed actors. I am using runtime generation in order to generate proxy objects (actor ref).
Is there a chance to explicitely call instrumentation from my code with a given class ?
By nature, I know in advance where to instrument (at least I believe i know :) ). This would enable me to run without the commandline switch thingy.

**Comment by pron** [comment]
Yes. Use [this class](https://github.com/puniverse/quasar/blob/master/quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/QuasarInstrumentor.java). See how it's used by the [Java agent](https://github.com/puniverse/quasar/blob/master/quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/JavaAgent.java), [AOT instrumentation task](https://github.com/puniverse/quasar/blob/master/quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/InstrumentationTask.java), and [instrumenting ClassLoader](https://github.com/puniverse/quasar/blob/master/quasar-core/src/main/java/co/paralleluniverse/fibers/instrument/QuasarURLClassLoader.java).

**Comment by RuedigerMoeller** [comment]
Thx for quick response :)
